### ISSUE TITLE
Can't get IDL

### ISSUE THREAD

**Issue by gitmalong** [SenchaHQ/sencha#52]
```
yarn install
yarn idl:generate
```
➤ YN0000: └ Completed in 4s 397ms
➤ YN0000: Done with warnings in 59s 962ms
Parsing IDL for cpamm
thread 'main' panicked at 'Could not resolve Accounts symbol', lang/syn/src/idl/file.rs:450:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Could not parse IDL

**Comment by andrewtian** [comment]
Make sure you're on the latest anchor.
